Repository Leets-Makers/Weeth-BE, pull requests merged in 2024-12, with the labels that each got.

#80 Refactor #80 user entity에서 refreshToken 제거
  src/main/java/leets/weeth/domain/user/domain/entity/User.java
  src/main/java/leets/weeth/domain/user/domain/repository/UserRepository.java
Labels: refactor

#87 Feat#86 다수 게시물 조회 시 파일 첨부 여부 표시 기능 추가
  src/main/java/leets/weeth/domain/board/application/dto/NoticeDTO.java
  src/main/java/leets/weeth/domain/board/application/dto/PostDTO.java
  src/main/java/leets/weeth/domain/board/application/mapper/NoticeMapper.java
  src/main/java/leets/weeth/domain/board/application/mapper/PostMapper.java
  src/main/java/leets/weeth/domain/board/application/usecase/NoticeUsecaseImpl.java
  src/main/java/leets/weeth/domain/board/application/usecase/PostUseCaseImpl.java
  src/main/java/leets/weeth/domain/file/domain/service/FileGetService.java
Labels: feature

#89 Refactor #89 UserUseCase 분리 및 리프레시 토큰 수정
  src/main/java/leets/weeth/domain/user/application/usecase/UserManageUseCase.java
  src/main/java/leets/weeth/domain/user/application/usecase/UserManageUseCaseImpl.java
  src/main/java/leets/weeth/domain/user/application/usecase/UserUseCase.java
  src/main/java/leets/weeth/domain/user/application/usecase/UserUseCaseImpl.java
  src/main/java/leets/weeth/domain/user/presentation/UserAdminController.java
  src/main/java/leets/weeth/domain/user/presentation/UserController.java
  src/main/java/leets/weeth/global/auth/jwt/application/usecase/JwtManageUseCase.java
Labels: refactor

#91 Refactor #91 소셜 로그인 연동 기능 구현
  src/main/java/leets/weeth/domain/user/application/dto/request/UserRequestDto.java
  src/main/java/leets/weeth/domain/user/application/dto/response/UserResponseDto.java
  src/main/java/leets/weeth/domain/user/application/exception/PasswordMismatchException.java
  src/main/java/leets/weeth/domain/user/application/exception/UserInActiveException.java
  src/main/java/leets/weeth/domain/user/application/mapper/UserMapper.java
  src/main/java/leets/weeth/domain/user/application/usecase/UserManageUseCase.java
  src/main/java/leets/weeth/domain/user/application/usecase/UserManageUseCaseImpl.java
  src/main/java/leets/weeth/domain/user/application/usecase/UserUseCase.java
  src/main/java/leets/weeth/domain/user/application/usecase/UserUseCaseImpl.java
  src/main/java/leets/weeth/domain/user/domain/entity/User.java
  src/main/java/leets/weeth/domain/user/domain/entity/enums/LoginStatus.java
  src/main/java/leets/weeth/domain/user/domain/repository/UserRepository.java
  src/main/java/leets/weeth/domain/user/domain/service/UserGetService.java
  src/main/java/leets/weeth/domain/user/presentation/ResponseMessage.java
  src/main/java/leets/weeth/domain/user/presentation/UserController.java
  src/main/java/leets/weeth/global/config/SecurityConfig.java
Labels: feature, refactor

#92 Feat #92 전역 내정보 조회
  src/main/java/leets/weeth/domain/user/application/dto/response/UserResponseDto.java
  src/main/java/leets/weeth/domain/user/application/mapper/UserMapper.java
  src/main/java/leets/weeth/domain/user/application/usecase/UserUseCase.java
  src/main/java/leets/weeth/domain/user/application/usecase/UserUseCaseImpl.java
  src/main/java/leets/weeth/domain/user/presentation/UserAdminController.java
  src/main/java/leets/weeth/domain/user/presentation/UserController.java
Labels: feature
