Repository Leets-Makers/Weeth-BE, pull requests merged in 2024-11, with the labels that each got.

#66 Rafactor #66 jwt 로직 수정
  .github/workflows/dev.yml
  build.gradle
  src/main/java/leets/weeth/domain/user/application/dto/request/UserRequestDto.java
  src/main/java/leets/weeth/domain/user/application/dto/response/UserResponseDto.java
  src/main/java/leets/weeth/domain/user/application/mapper/UserMapper.java
  src/main/java/leets/weeth/domain/user/application/usecase/UserManageUseCase.java
  src/main/java/leets/weeth/domain/user/application/usecase/UserManageUseCaseImpl.java
  src/main/java/leets/weeth/domain/user/application/usecase/UserUseCase.java
  src/main/java/leets/weeth/domain/user/application/usecase/UserUseCaseImpl.java
  src/main/java/leets/weeth/domain/user/domain/entity/User.java
  src/main/java/leets/weeth/domain/user/domain/entity/enums/LoginStatus.java
  src/main/java/leets/weeth/domain/user/domain/service/UserGetService.java
  src/main/java/leets/weeth/domain/user/domain/service/UserUpdateService.java
  src/main/java/leets/weeth/domain/user/presentation/ResponseMessage.java
  src/main/java/leets/weeth/domain/user/presentation/UserAdminController.java
  src/main/java/leets/weeth/domain/user/presentation/UserController.java
  src/main/java/leets/weeth/global/auth/jwt/application/dto/JwtDto.java
  src/main/java/leets/weeth/global/auth/jwt/application/usecase/JwtManageUseCase.java
  src/main/java/leets/weeth/global/auth/jwt/exception/InvalidTokenException.java
  src/main/java/leets/weeth/global/auth/jwt/exception/RedisTokenNotFoundException.java
  src/main/java/leets/weeth/global/auth/jwt/exception/TokenNotFoundException.java
  src/main/java/leets/weeth/global/auth/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/leets/weeth/global/auth/jwt/service/JwtProvider.java
  src/main/java/leets/weeth/global/auth/jwt/service/JwtRedisService.java
  src/main/java/leets/weeth/global/auth/jwt/service/JwtService.java
  src/main/java/leets/weeth/global/auth/kakao/KakaoAuthService.java
  src/main/java/leets/weeth/global/auth/kakao/dto/KakaoAccount.java
  src/main/java/leets/weeth/global/auth/kakao/dto/KakaoTokenResponse.java
  src/main/java/leets/weeth/global/auth/kakao/dto/KakaoUserInfoResponse.java
  src/main/java/leets/weeth/global/auth/login/handler/LoginFailureHandler.java
  src/main/java/leets/weeth/global/auth/login/handler/LoginSuccessHandler.java
  src/main/java/leets/weeth/global/config/RedisConfig.java
  src/main/java/leets/weeth/global/config/SecurityConfig.java
  src/main/java/leets/weeth/global/config/WebMvcConfig.java
  src/main/java/leets/weeth/global/config/swagger/SwaggerConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: feature, refactor

#71 Feat #71 파일 도메인 분리 및 presigned url 도입
  build.gradle
  src/main/java/leets/weeth/domain/account/application/usecase/ReceiptUseCaseImpl.java
  src/main/java/leets/weeth/domain/board/application/usecase/NoticeUsecaseImpl.java
  src/main/java/leets/weeth/domain/board/application/usecase/PostUseCaseImpl.java
  src/main/java/leets/weeth/domain/file/application/dto/request/FileSaveRequest.java
  src/main/java/leets/weeth/domain/file/application/dto/request/FileUpdateRequest.java
  src/main/java/leets/weeth/domain/file/application/dto/response/FileResponse.java
  src/main/java/leets/weeth/domain/file/application/dto/response/UrlResponse.java
  src/main/java/leets/weeth/domain/file/application/mapper/FileMapper.java
  src/main/java/leets/weeth/domain/file/application/usecase/FileManageUseCase.java
  src/main/java/leets/weeth/domain/file/domain/entity/File.java
  src/main/java/leets/weeth/domain/file/domain/repository/FileRepository.java
  src/main/java/leets/weeth/domain/file/domain/service/FileGetService.java
  src/main/java/leets/weeth/domain/file/domain/service/FileSaveService.java
  src/main/java/leets/weeth/domain/file/domain/service/FileUpdateService.java
  src/main/java/leets/weeth/domain/file/domain/service/PreSignedService.java
  src/main/java/leets/weeth/domain/file/presentation/FileController.java
  src/main/java/leets/weeth/domain/file/presentation/ResponseMessage.java
  src/main/java/leets/weeth/domain/file/service/S3Service.java
  src/main/java/leets/weeth/global/config/AwsS3Config.java
  src/main/resources/application-local.yml
Labels: feature, refactor

#75 Feat #75 멤버 리스트 반환 수정 및 멤버 상세 조회 추가
  src/main/java/leets/weeth/domain/user/application/dto/response/UserResponseDto.java
  src/main/java/leets/weeth/domain/user/application/mapper/UserMapper.java
  src/main/java/leets/weeth/domain/user/application/usecase/UserUseCase.java
  src/main/java/leets/weeth/domain/user/application/usecase/UserUseCaseImpl.java
  src/main/java/leets/weeth/domain/user/presentation/ResponseMessage.java
  src/main/java/leets/weeth/domain/user/presentation/UserController.java
Labels: feature, refactor

#78 Feat #77 영수증 수정 기능 추가
  src/main/java/leets/weeth/domain/account/application/dto/ReceiptDTO.java
  src/main/java/leets/weeth/domain/account/application/usecase/ReceiptUseCase.java
  src/main/java/leets/weeth/domain/account/application/usecase/ReceiptUseCaseImpl.java
  src/main/java/leets/weeth/domain/account/domain/entity/Receipt.java
  src/main/java/leets/weeth/domain/account/domain/service/ReceiptUpdateService.java
  src/main/java/leets/weeth/domain/account/presentation/ReceiptAdminController.java
  src/main/java/leets/weeth/domain/account/presentation/ResponseMessage.java
Labels: feature

#76 Refactor #76 소셜 로그인을 위한 더미 패스워드 도입
  src/main/java/leets/weeth/global/auth/jwt/filter/JwtAuthenticationProcessingFilter.java
Labels: refactor

#85 Feat #84 소셜 로그인 후 회원가입 정보 입력 api 구현
  src/main/java/leets/weeth/domain/user/application/dto/request/UserRequestDto.java
  src/main/java/leets/weeth/domain/user/application/usecase/UserUseCase.java
  src/main/java/leets/weeth/domain/user/application/usecase/UserUseCaseImpl.java
  src/main/java/leets/weeth/domain/user/domain/entity/User.java
  src/main/java/leets/weeth/domain/user/domain/service/UserUpdateService.java
  src/main/java/leets/weeth/domain/user/presentation/UserController.java
Labels: feature
