Repository Leets-Makers/Weeth-BE, pull requests merged in 2024-08, with the labels that each got.

#5 #5 Feat: 유저 로그인 및 회원가입
  src/main/java/leets/weeth/domain/user/application/usecase/UserUseCase.java
  src/main/java/leets/weeth/domain/user/application/usecase/UserUseCaseImpl.java
  src/main/java/leets/weeth/domain/user/domain/service/UserSaveService.java
  src/main/java/leets/weeth/domain/user/presentation/UserController.java
  src/main/java/leets/weeth/domain/user/presentation/controller/UserController.java
Labels: feature

#7 #7 Refactor: 이벤트 생성/수정 시, 유저 객체 매핑
  src/main/java/leets/weeth/domain/schedule/application/mapper/EventMapper.java
  src/main/java/leets/weeth/domain/schedule/application/usecase/EventUseCase.java
  src/main/java/leets/weeth/domain/schedule/application/usecase/EventUseCaseImpl.java
  src/main/java/leets/weeth/domain/schedule/domain/service/EventUpdateService.java
  src/main/java/leets/weeth/domain/schedule/presentation/EventAdminController.java
  src/main/java/leets/weeth/domain/user/domain/service/UserGetService.java
Labels: refactor

#9 #9 Feat: 이벤트 삭제
  src/main/java/leets/weeth/domain/schedule/application/usecase/EventUseCase.java
  src/main/java/leets/weeth/domain/schedule/application/usecase/EventUseCaseImpl.java
  src/main/java/leets/weeth/domain/schedule/domain/service/EventDeleteService.java
  src/main/java/leets/weeth/domain/schedule/presentation/EventAdminController.java
Labels: feature

#12 #2/feat/게시판 도메인 개발
  src/main/java/leets/weeth/domain/board/application/dto/BoardDTO.java
  src/main/java/leets/weeth/domain/board/application/dto/NoticeDTO.java
  src/main/java/leets/weeth/domain/board/application/dto/PostDTO.java
  src/main/java/leets/weeth/domain/board/application/mapper/NoticeMapper.java
  src/main/java/leets/weeth/domain/board/application/mapper/PostMapper.java
  src/main/java/leets/weeth/domain/board/application/usecase/BoardUseCase.java
  src/main/java/leets/weeth/domain/board/application/usecase/BoardUseCaseImpl.java
  src/main/java/leets/weeth/domain/board/application/usecase/NoticeUsecase.java
  src/main/java/leets/weeth/domain/board/application/usecase/NoticeUsecaseImpl.java
  src/main/java/leets/weeth/domain/board/application/usecase/PostUseCaseImpl.java
  src/main/java/leets/weeth/domain/board/application/usecase/PostUsecase.java
  src/main/java/leets/weeth/domain/board/domain/entity/Board.java
  src/main/java/leets/weeth/domain/board/domain/entity/Notice.java
  src/main/java/leets/weeth/domain/board/domain/entity/Post.java
  src/main/java/leets/weeth/domain/board/domain/repository/NoticeRepository.java
  src/main/java/leets/weeth/domain/board/domain/repository/PostRepository.java
  src/main/java/leets/weeth/domain/board/domain/service/NoticeDeleteService.java
  src/main/java/leets/weeth/domain/board/domain/service/NoticeFindService.java
  src/main/java/leets/weeth/domain/board/domain/service/NoticeSaveService.java
  src/main/java/leets/weeth/domain/board/domain/service/NoticeUpdateService.java
  src/main/java/leets/weeth/domain/board/domain/service/PostDeleteService.java
  src/main/java/leets/weeth/domain/board/domain/service/PostFindService.java
  src/main/java/leets/weeth/domain/board/domain/service/PostSaveService.java
  src/main/java/leets/weeth/domain/board/domain/service/PostUpdateService.java
  src/main/java/leets/weeth/domain/board/presentation/BoardController.java
  src/main/java/leets/weeth/domain/board/presentation/NoticeAdminController.java
  src/main/java/leets/weeth/domain/board/presentation/PostController.java
Labels: feature

#15 #15 Feat: 파일 업로더 구현
  src/main/java/leets/weeth/domain/file/converter/FileListConverter.java
  src/main/java/leets/weeth/domain/file/service/FileSaveService.java
Labels: feature

#17 #17 Fix: NPE 해결 및 스케줄 시작 시간으로 정렬
  src/main/java/leets/weeth/domain/schedule/application/usecase/ScheduleUseCaseImpl.java
Labels: fix

#19 #19 Feat: 유저 관련 도메인 개발
  src/main/java/leets/weeth/domain/user/application/mapper/UserMapper.java
  src/main/java/leets/weeth/domain/user/application/usecase/UserUseCase.java
  src/main/java/leets/weeth/domain/user/application/usecase/UserUseCaseImpl.java
  src/main/java/leets/weeth/domain/user/domain/entity/User.java
  src/main/java/leets/weeth/domain/user/domain/entity/enums/Department.java
  src/main/java/leets/weeth/domain/user/domain/repository/UserRepository.java
  src/main/java/leets/weeth/domain/user/domain/service/UserDeleteService.java
  src/main/java/leets/weeth/domain/user/domain/service/UserGetService.java
  src/main/java/leets/weeth/domain/user/domain/service/UserService.java
  src/main/java/leets/weeth/domain/user/domain/service/UserUpdateService.java
  src/main/java/leets/weeth/domain/user/presentation/UserAdminController.java
  src/main/java/leets/weeth/domain/user/presentation/UserController.java
  src/main/java/leets/weeth/global/auth/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/leets/weeth/global/auth/login/filter/CustomJsonUsernamePasswordAuthenticationFilter.java
Labels: feature

#21 #20 Refactor: 업데이트 로직 수정
  src/main/java/leets/weeth/domain/schedule/application/usecase/EventUseCaseImpl.java
  src/main/java/leets/weeth/domain/schedule/application/usecase/MeetingUseCaseImpl.java
  src/main/java/leets/weeth/domain/schedule/domain/entity/Event.java
  src/main/java/leets/weeth/domain/schedule/domain/entity/Meeting.java
  src/main/java/leets/weeth/domain/schedule/domain/entity/Schedule.java
  src/main/java/leets/weeth/domain/schedule/domain/service/EventUpdateService.java
  src/main/java/leets/weeth/domain/schedule/domain/service/MeetingUpdateService.java
  src/main/java/leets/weeth/domain/user/domain/service/UserUpdateService.java
Labels: refactor

#24 #24 Feat: 출석 도메인 개발
  src/main/java/leets/weeth/domain/attendance/application/dto/AttendanceDTO.java
  src/main/java/leets/weeth/domain/attendance/application/mapper/AttendanceMapper.java
  src/main/java/leets/weeth/domain/attendance/application/usecase/AttendanceUseCase.java
  src/main/java/leets/weeth/domain/attendance/application/usecase/AttendanceUseCaseImpl.java
  src/main/java/leets/weeth/domain/attendance/domain/entity/Attendance.java
  src/main/java/leets/weeth/domain/attendance/domain/entity/enums/Status.java
  src/main/java/leets/weeth/domain/attendance/domain/repository/AttendanceRepository.java
  src/main/java/leets/weeth/domain/attendance/domain/service/AttendanceSaveService.java
  src/main/java/leets/weeth/domain/attendance/domain/service/AttendanceUpdateService.java
  src/main/java/leets/weeth/domain/attendance/presentation/AttendanceAdminController.java
  src/main/java/leets/weeth/domain/attendance/presentation/AttendanceController.java
  src/main/java/leets/weeth/domain/schedule/domain/entity/Meeting.java
  src/main/java/leets/weeth/domain/schedule/domain/repository/MeetingRepository.java
  src/main/java/leets/weeth/domain/schedule/domain/service/MeetingGetService.java
  src/main/java/leets/weeth/domain/user/application/usecase/UserUseCaseImpl.java
  src/main/java/leets/weeth/domain/user/domain/entity/User.java
  src/main/java/leets/weeth/global/common/error/exception/custom/CardinalNotFoundException.java
Labels: feature

#26 #26 Refactor: 출석 체크 로직 수정
  src/main/java/leets/weeth/domain/attendance/application/usecase/AttendanceUseCase.java
  src/main/java/leets/weeth/domain/attendance/application/usecase/AttendanceUseCaseImpl.java
  src/main/java/leets/weeth/domain/attendance/domain/entity/Attendance.java
  src/main/java/leets/weeth/domain/attendance/presentation/AttendanceController.java
Labels: refactor

#33 #33 Fix: 출석 도메인 오류 수정
  src/main/java/leets/weeth/domain/attendance/application/mapper/AttendanceMapper.java
  src/main/java/leets/weeth/domain/attendance/application/usecase/AttendanceUseCaseImpl.java
  src/main/java/leets/weeth/domain/attendance/domain/entity/Attendance.java
  src/main/java/leets/weeth/domain/attendance/domain/service/AttendanceUpdateService.java
  src/main/java/leets/weeth/domain/user/domain/entity/User.java
Labels: fix

#36 #36 Refactor: 게시판 패널티 리팩토링
  src/main/java/leets/weeth/domain/account/application/dto/ReceiptDTO.java
  src/main/java/leets/weeth/domain/account/application/mapper/ReceiptMapper.java
  src/main/java/leets/weeth/domain/account/domain/entity/Account.java
  src/main/java/leets/weeth/domain/account/domain/entity/Receipt.java
  src/main/java/leets/weeth/domain/board/domain/entity/enums/ResponseMessage.java
  src/main/java/leets/weeth/domain/board/presentation/NoticeAdminController.java
  src/main/java/leets/weeth/domain/board/presentation/PostController.java
  src/main/java/leets/weeth/domain/comment/domain/entity/enums/ResponseMessage.java
  src/main/java/leets/weeth/domain/comment/presentation/NoticeCommentController.java
  src/main/java/leets/weeth/domain/comment/presentation/PostCommentController.java
  src/main/java/leets/weeth/domain/penalty/application/usecase/PenaltyUsecaseImpl.java
  src/main/java/leets/weeth/domain/penalty/domain/entity/enums/ResponseMessage.java
  src/main/java/leets/weeth/domain/penalty/presentation/penaltyAdminController.java
  src/main/java/leets/weeth/domain/schedule/application/dto/EventDTO.java
  src/main/java/leets/weeth/domain/schedule/domain/entity/Event.java
  src/main/java/leets/weeth/global/common/error/exception/ExceptionType.java
Labels: refactor

#41 #41 Feat: 시간 Validator 구현
  src/main/java/leets/weeth/domain/schedule/application/annotation/ScheduleTimeCheck.java
  src/main/java/leets/weeth/domain/schedule/application/dto/EventDTO.java
  src/main/java/leets/weeth/domain/schedule/application/dto/MeetingDTO.java
  src/main/java/leets/weeth/domain/schedule/application/dto/ScheduleDTO.java
  src/main/java/leets/weeth/domain/schedule/application/validator/ScheduleTimeCheckValidator.java
  src/main/java/leets/weeth/domain/schedule/domain/entity/Schedule.java
Labels: feature

#42 #40 Feat: 어드민페이지 구현
  .gitignore
  src/main/java/leets/weeth/domain/board/application/usecase/NoticeUsecaseImpl.java
  src/main/java/leets/weeth/domain/board/domain/repository/NoticeRepository.java
  src/main/java/leets/weeth/domain/board/domain/repository/PostRepository.java
  src/main/java/leets/weeth/domain/board/domain/service/NoticeFindService.java
  src/main/java/leets/weeth/domain/board/domain/service/PostFindService.java
  src/main/java/leets/weeth/domain/schedule/application/mapper/MeetingMapper.java
  src/main/java/leets/weeth/domain/schedule/application/usecase/MeetingUseCase.java
  src/main/java/leets/weeth/domain/schedule/application/usecase/MeetingUseCaseImpl.java
  src/main/java/leets/weeth/domain/schedule/domain/service/MeetingGetService.java
  src/main/java/leets/weeth/domain/schedule/presentation/MeetingAdminController.java
  src/main/java/leets/weeth/domain/user/application/dto/UserDTO.java
  src/main/java/leets/weeth/global/common/controller/ThymeLeafController.java
  src/main/java/leets/weeth/global/config/SecurityConfig.java
  src/main/resources/static/js/account.js
  src/main/resources/static/js/attendance.js
  src/main/resources/static/js/meeting.js
  src/main/resources/static/js/members.js
  src/main/resources/static/js/penalty.js
  src/main/resources/templates/account.html
  src/main/resources/templates/fragments/logout.html
  src/main/resources/templates/fragments/sidebar.html
  src/main/resources/templates/login.html
  src/main/resources/templates/meeting.html
  src/main/resources/templates/member.html
  src/main/resources/templates/penalty.html
Labels: feature

#46 #46 Refactor: 대댓글 중복제거 코드 리팩토링
  src/main/java/leets/weeth/domain/board/application/dto/NoticeDTO.java
  src/main/java/leets/weeth/domain/board/application/dto/PostDTO.java
  src/main/java/leets/weeth/domain/board/application/mapper/NoticeMapper.java
  src/main/java/leets/weeth/domain/board/application/mapper/PostMapper.java
  src/main/java/leets/weeth/domain/board/application/usecase/NoticeUsecase.java
  src/main/java/leets/weeth/domain/board/application/usecase/NoticeUsecaseImpl.java
  src/main/java/leets/weeth/domain/board/application/usecase/PostUseCaseImpl.java
  src/main/java/leets/weeth/domain/board/application/usecase/PostUsecase.java
  src/main/java/leets/weeth/domain/board/presentation/NoticeController.java
  src/main/java/leets/weeth/domain/board/presentation/PostController.java
  src/main/java/leets/weeth/domain/comment/application/mapper/CommentMapper.java
  src/main/java/leets/weeth/domain/comment/application/usecase/NoticeCommentUsecaseImpl.java
Labels: refactor

#48 #48 Feat: 댓글삭제시 댓글수 다시계산
  src/main/java/leets/weeth/domain/board/application/usecase/NoticeUsecaseImpl.java
  src/main/java/leets/weeth/domain/board/application/usecase/PostUseCaseImpl.java
  src/main/java/leets/weeth/domain/board/domain/entity/Board.java
  src/main/java/leets/weeth/domain/board/domain/entity/Notice.java
  src/main/java/leets/weeth/domain/board/domain/entity/Post.java
  src/main/java/leets/weeth/domain/comment/application/usecase/NoticeCommentUsecaseImpl.java
  src/main/java/leets/weeth/domain/comment/application/usecase/PostCommentUsecaseImpl.java
Labels: feature
