Repository Leets-Makers/Weeth-BE, pull requests merged in 2025-01, with the labels that each got.

#97 Refactor #97 일정 생성 로직 수정
  src/main/java/leets/weeth/domain/attendance/application/usecase/AttendanceUseCaseImpl.java
  src/main/java/leets/weeth/domain/attendance/domain/repository/AttendanceRepository.java
  src/main/java/leets/weeth/domain/attendance/domain/service/AttendanceDeleteService.java
  src/main/java/leets/weeth/domain/attendance/domain/service/AttendanceGetService.java
  src/main/java/leets/weeth/domain/attendance/domain/service/AttendanceSaveService.java
  src/main/java/leets/weeth/domain/attendance/domain/service/AttendanceUpdateService.java
  src/main/java/leets/weeth/domain/file/service/S3Service.java
  src/main/java/leets/weeth/domain/schedule/application/mapper/MeetingMapper.java
  src/main/java/leets/weeth/domain/schedule/application/usecase/EventUseCaseImpl.java
  src/main/java/leets/weeth/domain/schedule/application/usecase/MeetingUseCaseImpl.java
  src/main/java/leets/weeth/domain/schedule/domain/entity/Meeting.java
  src/main/java/leets/weeth/domain/user/application/usecase/UserManageUseCaseImpl.java
  src/main/java/leets/weeth/domain/user/domain/entity/User.java
  src/main/java/leets/weeth/domain/user/domain/repository/UserRepository.java
  src/main/java/leets/weeth/domain/user/domain/service/UserGetService.java
  src/main/java/leets/weeth/global/config/AwsS3Config.java
Labels: refactor

#99 Refactor#94 멤버 조회 방식 변경 및 추가
  src/main/java/leets/weeth/domain/user/application/exception/InvalidUserOrderException.java
  src/main/java/leets/weeth/domain/user/application/exception/StatusNotFoundException.java
  src/main/java/leets/weeth/domain/user/application/usecase/UserManageUseCase.java
  src/main/java/leets/weeth/domain/user/application/usecase/UserManageUseCaseImpl.java
  src/main/java/leets/weeth/domain/user/domain/entity/enums/StatusPriority.java
  src/main/java/leets/weeth/domain/user/domain/entity/enums/UsersOrderBy.java
  src/main/java/leets/weeth/domain/user/domain/repository/UserRepository.java
  src/main/java/leets/weeth/domain/user/domain/service/UserGetService.java
  src/main/java/leets/weeth/domain/user/presentation/UserAdminController.java
Labels: refactor

#101 Fix #101 api 경로 해제
  src/main/java/leets/weeth/domain/user/presentation/UserController.java
  src/main/java/leets/weeth/global/config/SecurityConfig.java
Labels: fix

#103 Feat #103 단일 출석 반환 Api 및 변경 로직 구현
  src/main/java/leets/weeth/domain/attendance/application/dto/AttendanceDTO.java
  src/main/java/leets/weeth/domain/attendance/application/mapper/AttendanceMapper.java
  src/main/java/leets/weeth/domain/attendance/application/usecase/AttendanceUseCase.java
  src/main/java/leets/weeth/domain/attendance/application/usecase/AttendanceUseCaseImpl.java
  src/main/java/leets/weeth/domain/attendance/domain/service/AttendanceGetService.java
  src/main/java/leets/weeth/domain/attendance/presentation/AttendanceAdminController.java
  src/main/java/leets/weeth/domain/attendance/presentation/ResponseMessage.java
Labels: feature

#104 Refactor #98 개발서버 무중단 배포 cicd 구축
  .github/workflows/dev.yml
  src/main/resources/application-dev.yml
Labels: refactor

#106 Refactor #106 기수 테이블 분리
  src/main/java/leets/weeth/domain/attendance/application/usecase/AttendanceUseCaseImpl.java
  src/main/java/leets/weeth/domain/penalty/application/usecase/PenaltyUsecaseImpl.java
  src/main/java/leets/weeth/domain/schedule/application/usecase/MeetingUseCaseImpl.java
  src/main/java/leets/weeth/domain/user/application/dto/request/CardinalSaveRequest.java
  src/main/java/leets/weeth/domain/user/application/dto/response/CardinalResponse.java
  src/main/java/leets/weeth/domain/user/application/dto/response/UserCardinalDto.java
  src/main/java/leets/weeth/domain/user/application/exception/DuplicateCardinalException.java
  src/main/java/leets/weeth/domain/user/application/mapper/CardinalMapper.java
  src/main/java/leets/weeth/domain/user/application/mapper/UserMapper.java
  src/main/java/leets/weeth/domain/user/application/usecase/CardinalUseCase.java
  src/main/java/leets/weeth/domain/user/application/usecase/UserManageUseCaseImpl.java
  src/main/java/leets/weeth/domain/user/application/usecase/UserUseCase.java
  src/main/java/leets/weeth/domain/user/application/usecase/UserUseCaseImpl.java
  src/main/java/leets/weeth/domain/user/domain/entity/Cardinal.java
  src/main/java/leets/weeth/domain/user/domain/entity/User.java
  src/main/java/leets/weeth/domain/user/domain/entity/UserCardinal.java
  src/main/java/leets/weeth/domain/user/domain/repository/CardinalRepository.java
  src/main/java/leets/weeth/domain/user/domain/repository/UserCardinalRepository.java
  src/main/java/leets/weeth/domain/user/domain/repository/UserRepository.java
  src/main/java/leets/weeth/domain/user/domain/service/CardinalGetService.java
  src/main/java/leets/weeth/domain/user/domain/service/CardinalSaveService.java
  src/main/java/leets/weeth/domain/user/domain/service/UserCardinalGetService.java
  src/main/java/leets/weeth/domain/user/domain/service/UserCardinalSaveService.java
  src/main/java/leets/weeth/domain/user/domain/service/UserGetService.java
  src/main/java/leets/weeth/domain/user/domain/service/UserUpdateService.java
  src/main/java/leets/weeth/domain/user/presentation/CardinalController.java
  src/main/java/leets/weeth/domain/user/presentation/ResponseMessage.java
  src/main/java/leets/weeth/domain/user/presentation/UserController.java
Labels: refactor

#108 Feat #108 영수증 사용처 추가
  src/main/java/leets/weeth/domain/account/application/dto/ReceiptDTO.java
  src/main/java/leets/weeth/domain/account/domain/entity/Receipt.java
Labels: feature

#110 Feat #110 당일 출석 상태 함께 반환
  src/main/java/leets/weeth/domain/attendance/application/dto/AttendanceDTO.java
  src/main/java/leets/weeth/domain/attendance/application/mapper/AttendanceMapper.java
Labels: feature

#111 Refactor#111 글 조회시 포지션과 역할 같이 반환하도록 수정
  src/main/java/leets/weeth/domain/board/application/dto/NoticeDTO.java
  src/main/java/leets/weeth/domain/board/application/dto/PostDTO.java
  src/main/java/leets/weeth/domain/board/application/mapper/NoticeMapper.java
  src/main/java/leets/weeth/domain/board/application/mapper/PostMapper.java
  src/main/java/leets/weeth/domain/board/application/usecase/NoticeUsecaseImpl.java
  src/main/java/leets/weeth/domain/board/application/usecase/PostUseCaseImpl.java
  src/main/java/leets/weeth/domain/comment/application/dto/CommentDTO.java
  src/main/java/leets/weeth/domain/comment/application/mapper/CommentMapper.java
Labels: refactor
