Repository Leets-Makers/Weeth-BE, pull requests merged in 2025-03, with the labels that each got.

#148 refactor #148 원본 파일명 제거 후 UUID.확장자로 수정
  src/main/java/leets/weeth/domain/file/domain/service/PreSignedService.java
Labels: refactor

#150 Refactor #150 게시판 관련 엔드포인트 수정
  src/main/java/leets/weeth/domain/board/presentation/PostController.java
  src/main/java/leets/weeth/domain/comment/presentation/PostCommentController.java
Labels: refactor

#152 fix #152 출석 횟수와 동시에 결석횟수 처리하도록 수정
  src/main/java/leets/weeth/domain/attendance/application/usecase/AttendanceUseCaseImpl.java
Labels: refactor, fix

#158 Refactor #158 기수 정보 조회 시 기수 크기로 정렬한 후 반환
  src/main/java/leets/weeth/domain/user/domain/repository/CardinalRepository.java
  src/main/java/leets/weeth/domain/user/domain/repository/UserCardinalRepository.java
  src/main/java/leets/weeth/domain/user/domain/service/CardinalGetService.java
  src/main/java/leets/weeth/domain/user/domain/service/UserCardinalGetService.java
Labels: refactor

#160 Refactor #160 학과 enum 필드 추가
  src/main/java/leets/weeth/domain/user/domain/entity/enums/Department.java
Labels: refactor

#166 Refactor #166 개발 서버 CICD 일부 수정
  .github/workflows/dev.yml
Labels: refactor

#167 Refactor #167 main cicd 및 환경변수 수정
  .github/workflows/CICD.yml
  .github/workflows/dev.yml
  src/main/resources/application-prod.yml
Labels: refactor

#165 Refactor #165 어드민 단일 출석 변경 수정
  src/main/java/leets/weeth/domain/attendance/application/usecase/AttendanceUseCaseImpl.java
  src/main/java/leets/weeth/domain/attendance/presentation/AttendanceAdminController.java
Labels: refactor

#156 Feat#155 게시판 검색 기능 추가
  src/main/java/leets/weeth/domain/board/application/exception/NoSearchResultException.java
  src/main/java/leets/weeth/domain/board/application/usecase/PostUseCaseImpl.java
  src/main/java/leets/weeth/domain/board/application/usecase/PostUsecase.java
  src/main/java/leets/weeth/domain/board/domain/repository/PostRepository.java
  src/main/java/leets/weeth/domain/board/domain/service/PostFindService.java
  src/main/java/leets/weeth/domain/board/presentation/PostController.java
Labels: feature
