Repository Leets-Makers/Weeth-BE, pull requests merged in 2025-02, with the labels that each got.

#115 Feat #115 멤버 조회
  src/main/java/leets/weeth/domain/user/application/mapper/CardinalMapper.java
  src/main/java/leets/weeth/domain/user/application/usecase/UserUseCase.java
  src/main/java/leets/weeth/domain/user/application/usecase/UserUseCaseImpl.java
  src/main/java/leets/weeth/domain/user/domain/repository/UserRepository.java
  src/main/java/leets/weeth/domain/user/domain/service/UserGetService.java
  src/main/java/leets/weeth/domain/user/presentation/UserController.java
Labels: feature, refactor

#116 Refactor #116 일정 생성 로직 수정
  src/main/java/leets/weeth/domain/attendance/application/dto/AttendanceDTO.java
  src/main/java/leets/weeth/domain/attendance/application/mapper/AttendanceMapper.java
  src/main/java/leets/weeth/domain/schedule/application/dto/EventDTO.java
  src/main/java/leets/weeth/domain/schedule/application/dto/MeetingDTO.java
  src/main/java/leets/weeth/domain/schedule/application/dto/ScheduleDTO.java
  src/main/java/leets/weeth/domain/schedule/application/mapper/EventMapper.java
  src/main/java/leets/weeth/domain/schedule/application/mapper/MeetingMapper.java
  src/main/java/leets/weeth/domain/schedule/application/usecase/EventUseCase.java
  src/main/java/leets/weeth/domain/schedule/application/usecase/EventUseCaseImpl.java
  src/main/java/leets/weeth/domain/schedule/application/usecase/MeetingUseCase.java
  src/main/java/leets/weeth/domain/schedule/application/usecase/MeetingUseCaseImpl.java
  src/main/java/leets/weeth/domain/schedule/application/usecase/ScheduleUseCase.java
  src/main/java/leets/weeth/domain/schedule/application/usecase/ScheduleUseCaseImpl.java
  src/main/java/leets/weeth/domain/schedule/domain/entity/Event.java
  src/main/java/leets/weeth/domain/schedule/domain/entity/Meeting.java
  src/main/java/leets/weeth/domain/schedule/domain/entity/Schedule.java
  src/main/java/leets/weeth/domain/schedule/domain/entity/enums/Type.java
  src/main/java/leets/weeth/domain/schedule/domain/repository/EventRepository.java
  src/main/java/leets/weeth/domain/schedule/domain/repository/MeetingRepository.java
  src/main/java/leets/weeth/domain/schedule/domain/service/EventGetService.java
  src/main/java/leets/weeth/domain/schedule/domain/service/EventUpdateService.java
  src/main/java/leets/weeth/domain/schedule/domain/service/MeetingGetService.java
  src/main/java/leets/weeth/domain/schedule/domain/service/MeetingUpdateService.java
  src/main/java/leets/weeth/domain/schedule/presentation/EventAdminController.java
  src/main/java/leets/weeth/domain/schedule/presentation/MeetingAdminController.java
  src/main/java/leets/weeth/domain/schedule/presentation/MeetingController.java
  src/main/java/leets/weeth/domain/schedule/presentation/ResponseMessage.java
  src/main/java/leets/weeth/domain/schedule/presentation/ScheduleController.java
  src/main/java/leets/weeth/domain/user/domain/repository/CardinalRepository.java
  src/main/java/leets/weeth/domain/user/domain/service/CardinalGetService.java
Labels: refactor

#119 Refactor #119 댓글 중복 조회 수정
  src/main/java/leets/weeth/domain/board/application/mapper/NoticeMapper.java
  src/main/java/leets/weeth/domain/board/application/mapper/PostMapper.java
  src/main/java/leets/weeth/domain/board/application/usecase/NoticeUsecaseImpl.java
  src/main/java/leets/weeth/domain/board/application/usecase/PostUseCaseImpl.java
  src/main/java/leets/weeth/domain/comment/application/mapper/CommentMapper.java
Labels: refactor

#113 refactor#112 어드민용 기수순 유저 조회 추가
  src/main/java/leets/weeth/domain/user/application/usecase/UserManageUseCaseImpl.java
  src/main/java/leets/weeth/domain/user/domain/repository/UserCardinalRepository.java
  src/main/java/leets/weeth/domain/user/domain/service/UserCardinalGetService.java
Labels: refactor

#120 Refactor #120 회원가입 시 email 추가
  src/main/java/leets/weeth/domain/user/application/dto/request/UserRequestDto.java
Labels: refactor

#124 Fix #124 멤버 상세조회 시 role 추가 반환
  src/main/java/leets/weeth/domain/user/application/dto/response/UserResponseDto.java
Labels: fix

#128 Feat #128 정기모임 리스트
  src/main/java/leets/weeth/domain/attendance/presentation/AttendanceAdminController.java
  src/main/java/leets/weeth/domain/attendance/presentation/ResponseMessage.java
  src/main/java/leets/weeth/domain/penalty/presentation/PenaltyAdminController.java
  src/main/java/leets/weeth/domain/schedule/application/dto/MeetingDTO.java
  src/main/java/leets/weeth/domain/schedule/application/mapper/MeetingMapper.java
  src/main/java/leets/weeth/domain/schedule/application/usecase/MeetingUseCase.java
  src/main/java/leets/weeth/domain/schedule/application/usecase/MeetingUseCaseImpl.java
Labels: feature

#126 Fix #126 내 정보 수정 시 비밀번호 입력 제거, 소셜 회원가입시 Email 유효성 검증 추가
  src/main/java/leets/weeth/domain/user/application/dto/request/UserRequestDto.java
  src/main/java/leets/weeth/domain/user/application/usecase/UserUseCaseImpl.java
  src/main/java/leets/weeth/domain/user/domain/entity/User.java
  src/main/java/leets/weeth/domain/user/domain/service/UserUpdateService.java
Labels: fix

#130 Fix #130 일정/정기모임 기수 반환
  src/main/java/leets/weeth/domain/schedule/application/dto/EventDTO.java
  src/main/java/leets/weeth/domain/schedule/application/dto/MeetingDTO.java
  src/main/java/leets/weeth/domain/schedule/presentation/MeetingController.java
Labels: fix

#137 Refactor #137 멤버 관리 API 리스트로 수정
  src/main/java/leets/weeth/domain/attendance/presentation/AttendanceAdminController.java
  src/main/java/leets/weeth/domain/schedule/application/dto/MeetingDTO.java
  src/main/java/leets/weeth/domain/schedule/application/usecase/MeetingUseCaseImpl.java
  src/main/java/leets/weeth/domain/schedule/domain/repository/MeetingRepository.java
  src/main/java/leets/weeth/domain/schedule/domain/service/MeetingGetService.java
  src/main/java/leets/weeth/domain/user/application/dto/request/UserRequestDto.java
  src/main/java/leets/weeth/domain/user/application/usecase/UserManageUseCase.java
  src/main/java/leets/weeth/domain/user/application/usecase/UserManageUseCaseImpl.java
  src/main/java/leets/weeth/domain/user/domain/service/UserGetService.java
  src/main/java/leets/weeth/domain/user/presentation/UserAdminController.java
Labels: refactor

#135 Feat #135 패널티 수정 API 구현
  src/main/java/leets/weeth/domain/penalty/application/dto/PenaltyDTO.java
  src/main/java/leets/weeth/domain/penalty/application/usecase/PenaltyUsecase.java
  src/main/java/leets/weeth/domain/penalty/application/usecase/PenaltyUsecaseImpl.java
  src/main/java/leets/weeth/domain/penalty/domain/entity/Penalty.java
  src/main/java/leets/weeth/domain/penalty/presentation/PenaltyAdminController.java
  src/main/java/leets/weeth/domain/penalty/presentation/ResponseMessage.java
Labels: feature

#133 Refactor #133 출석마감 자동화
  src/main/java/leets/weeth/WeethApplication.java
  src/main/java/leets/weeth/domain/attendance/domain/service/AttendanceScheduler.java
  src/main/java/leets/weeth/domain/schedule/domain/entity/Meeting.java
  src/main/java/leets/weeth/domain/schedule/domain/entity/enums/MeetingStatus.java
  src/main/java/leets/weeth/domain/schedule/domain/repository/MeetingRepository.java
  src/main/java/leets/weeth/domain/schedule/domain/service/MeetingGetService.java
Labels: feature, refactor

#142 Feat #142 File 객체 BaseEntity를 상속 하도록 수정
  src/main/java/leets/weeth/domain/file/domain/entity/File.java
Labels: feature
