Repository Leets-Makers/Weeth-BE, pull requests merged in 2025-08, with the labels that each got.

#194 Fix #194 parts도 파트 게시글 생성시 동일하게 저장하도록 설정
  src/main/java/leets/weeth/domain/board/application/dto/PostDTO.java
  src/main/java/leets/weeth/domain/board/application/mapper/PostMapper.java
  src/main/java/leets/weeth/domain/board/presentation/PostController.java
Labels: bug, fix

#198 Feat #198 댓글 파일 첨부
  src/main/java/leets/weeth/domain/board/application/usecase/NoticeUsecaseImpl.java
  src/main/java/leets/weeth/domain/board/application/usecase/PostUseCaseImpl.java
  src/main/java/leets/weeth/domain/comment/application/dto/CommentDTO.java
  src/main/java/leets/weeth/domain/comment/application/mapper/CommentMapper.java
  src/main/java/leets/weeth/domain/comment/application/usecase/NoticeCommentUsecaseImpl.java
  src/main/java/leets/weeth/domain/comment/application/usecase/PostCommentUsecaseImpl.java
  src/main/java/leets/weeth/domain/file/application/mapper/FileMapper.java
  src/main/java/leets/weeth/domain/file/domain/entity/File.java
  src/main/java/leets/weeth/domain/file/domain/repository/FileRepository.java
  src/main/java/leets/weeth/domain/file/domain/service/FileGetService.java
Labels: feature

#204 Refactor #204 검색 API 분리
  src/main/java/leets/weeth/domain/board/application/dto/PostDTO.java
  src/main/java/leets/weeth/domain/board/application/usecase/NoticeUsecase.java
  src/main/java/leets/weeth/domain/board/application/usecase/NoticeUsecaseImpl.java
  src/main/java/leets/weeth/domain/board/application/usecase/PostUseCaseImpl.java
  src/main/java/leets/weeth/domain/board/application/usecase/PostUsecase.java
  src/main/java/leets/weeth/domain/board/domain/repository/NoticeRepository.java
  src/main/java/leets/weeth/domain/board/domain/repository/PostRepository.java
  src/main/java/leets/weeth/domain/board/domain/service/NoticeFindService.java
  src/main/java/leets/weeth/domain/board/domain/service/PostFindService.java
  src/main/java/leets/weeth/domain/board/presentation/NoticeController.java
  src/main/java/leets/weeth/domain/board/presentation/PostController.java
  src/main/java/leets/weeth/domain/board/presentation/ResponseMessage.java
Labels: feature, refactor

#199 Fix #199 게시판 반환 시간 수정
  src/main/java/leets/weeth/domain/board/application/dto/NoticeDTO.java
  src/main/java/leets/weeth/domain/board/application/mapper/PostMapper.java
Labels: fix
